USE redflix184;
DROP TABLE IF EXISTS pelicula;
CREATE TABLE IF NOT EXISTS pelicula (
id_pelicula INT NOT NULL PRIMARY KEY,
titulo VARCHAR(40) NOT NULL,
resumen VARCHAR(300) NOT NULL,
anio VARCHAR(40) NOT NULL
);
